# Generated by Django 3.2 on 2022-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intent_ID', models.CharField(max_length=200)),
                ('Intent_Name', models.CharField(max_length=200)),
                ('Traits', models.CharField(max_length=500)),
                ('Entities', models.CharField(max_length=200)),
                ('Utterence', models.CharField(max_length=500)),
                ('Entities_Rule', models.CharField(max_length=200)),
                ('the_json', models.JSONField()),
            ],
        ),
    ]
