# Generated by Django 3.2 on 2022-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Entities_Rule',
            new_name='Body',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Utterence',
            new_name='End',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Intent_ID',
            new_name='Intent',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Intent_Name',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='the_json',
            new_name='response',
        ),
        migrations.AddField(
            model_name='contact',
            name='Start',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Entities',
            field=models.CharField(max_length=500),
        ),
    ]
