# Generated by Django 3.2 on 2022-09-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20220901_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Text',
            new_name='Utterance',
        ),
    ]
