# Generated by Django 3.2 on 2022-09-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20220901_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Body',
            new_name='Utterance_Body',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='End',
            new_name='Utterance_End',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Start',
            new_name='Utterance_Start',
        ),
    ]
