# Generated by Django 3.2 on 2022-09-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20220901_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Entities',
            new_name='Utterance_Entities',
        ),
    ]
