# Generated by Django 3.2 on 2022-09-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_rename_entities_contact_utterance_entities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Utterance_Entities',
        ),
    ]
