# Generated by Django 3.2 on 2022-09-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_contact_utterance_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Utterance_Entities',
            field=models.CharField(choices=[('wit$location:location', 'wit$location:location'), ('wit$location:departure', 'wit$location:departure'), ('wit$location:destination', 'wit$location:destination')], default='green', max_length=500),
        ),
    ]
