# Generated by Django 3.2 on 2022-09-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_auto_20220922_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Shrug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.montact'),
        ),
        migrations.AlterField(
            model_name='montact',
            name='Intent',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
